name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GIT_PROFILE_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm install
      - run: npm run build
      - run: node dist/index.js
