name: Build and Commit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GIT_PROFILE_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm install
      - run: npm run build
      - run: node dist/index.js
